/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.18).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package de.apppointment.queuingserver.rest.controller;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import de.apppointment.queuingserver.rest.model.OfficeDto;
import io.swagger.annotations.*;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2020-03-21T14:46:54.089Z[GMT]")
@Api(value = "office", description = "the office API")
public interface OfficeApi {

    @ApiOperation(value = "", nickname = "officeOfficeIdDelete", notes = "", tags = {"office",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "success")})
    @RequestMapping(value = "/office/{officeId}", method = RequestMethod.DELETE)
    ResponseEntity<Void> officeOfficeIdDelete(@ApiParam(value = "", required = true) @PathVariable("officeId") String officeId);

    @ApiOperation(value = "", nickname = "officePost", notes = "", response = OfficeDto.class, tags = {"office",})
    @ApiResponses(value = {
            @ApiResponse(code = 200, message = "success", response = OfficeDto.class)})
    @RequestMapping(value = "/office", produces = {"application/json"}, consumes = {"application/json"}, method = RequestMethod.POST)
    ResponseEntity<OfficeDto> officePost(@ApiParam(value = "new medical office") @Valid @RequestBody OfficeDto body);

}
