swagger: '2.0'
info:
  description: Service for patient queue management
  version: 1.0.0
  title: QueueService
  contact: {}
host: 'localhost:8080'
basePath: /
tags:
  - name: office
    description: the office API
  - name: queue
    description: the queue API
paths:
  /office:
    post:
      tags:
        - office
      summary: officePost
      operationId: officePost
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: new medical office
          required: false
          schema:
            $ref: '#/definitions/Office'
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/Office'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/office/{officeId}':
    delete:
      tags:
        - office
      summary: officeOfficeIdDelete
      operationId: officeOfficeIdDelete
      produces:
        - '*/*'
      parameters:
        - name: officeId
          in: path
          description: officeId
          required: true
          type: string
      responses:
        '200':
          description: success
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
  '/queue/{officeId}/{day}':
    post:
      tags:
        - queue
      summary: queueOfficeIdDayPost
      operationId: queueOfficeIdDayPost
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: body
          description: the new patient
          required: false
          schema:
            $ref: '#/definitions/ApiAppointmentCreator'
        - name: day
          in: path
          description: day
          required: true
          type: string
          format: date
        - name: officeId
          in: path
          description: officeId
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/ApiAppointment'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
        - queue
      summary: queueOfficeIdDayPut
      description: replace the whole queue
      operationId: queueOfficeIdDayPut
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: body
          description: the new patient
          required: false
          schema:
            type: array
            items:
              $ref: '#/definitions/ApiAppointmentCreator'
        - name: day
          in: path
          description: day
          required: true
          type: string
          format: date
        - name: officeId
          in: path
          description: officeId
          required: true
          type: string
      responses:
        '200':
          description: success
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  '/queue/{officeId}/{day}/{patientId}':
    get:
      tags:
        - queue
      summary: queueOfficeIdDayPatientIdGet
      operationId: queueOfficeIdDayPatientIdGet
      produces:
        - application/json
      parameters:
        - name: day
          in: path
          description: day
          required: true
          type: string
          format: date
        - name: officeId
          in: path
          description: officeId
          required: true
          type: string
        - name: patientId
          in: path
          description: patientId
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/ApiAppointment'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
        - queue
      summary: queueOfficeIdDayPatientIdPut
      operationId: queueOfficeIdDayPatientIdPut
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: body
          required: false
          schema:
            $ref: '#/definitions/ApiAppointmentChange'
        - name: day
          in: path
          description: day
          required: true
          type: string
          format: date
        - name: officeId
          in: path
          description: officeId
          required: true
          type: string
        - name: patientId
          in: path
          description: patientId
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/ApiAppointment'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    delete:
      tags:
        - queue
      summary: queueOfficeIdDayPatientIdDelete
      operationId: queueOfficeIdDayPatientIdDelete
      produces:
        - application/json
      parameters:
        - name: day
          in: path
          description: day
          required: true
          type: string
          format: date
        - name: officeId
          in: path
          description: officeId
          required: true
          type: string
        - name: patientId
          in: path
          description: patientId
          required: true
          type: string
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/ApiAppointment'
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
definitions:
  ApiAppointment:
    type: object
    properties:
      estimateWaitingMinutes:
        type: integer
        format: int32
      estimatedInMinutes:
        type: integer
        format: int32
      patientId:
        type: string
      place:
        type: integer
        format: int32
      time:
        type: string
    title: ApiAppointment
    description: an appointment
  ApiAppointmentChange:
    type: object
    properties:
      notifications:
        type: array
        items:
          $ref: '#/definitions/ApiNotification'
    title: ApiAppointmentChange
    description: change an appointment
  ApiAppointmentCreator:
    type: object
    properties:
      estimatedInMinutes:
        type: integer
        format: int32
      notifications:
        type: array
        items:
          $ref: '#/definitions/ApiNotification'
      patientId:
        type: string
      time:
        type: string
    title: ApiAppointmentCreator
    description: an appointment
  ApiNotification:
    type: object
    properties:
      identifier:
        type: string
        description: 'appId when app, telefonnumber when sms, beeperId when beeper'
      type:
        type: string
        enum:
          - app
          - sms
          - beeper
    title: ApiNotification
  Office:
    type: object
    properties:
      id:
        type: string
    title: Office
    description: medical office
