openapi: 3.0.0
info:
  version: 1.0.0
  title: QueueService
  description: Service for patient queue management
  contact:
    name: TODO
tags:
  - name: office
    description: manage medical offices
  - name: queue
    description: managing the queue
servers:
  - url: /api
paths:
  /office:
    post:
      tags: [office]
      requestBody:
        description: new medical office
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Office'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Office'
  /office/{officeId}:
    delete:
      tags: [office]
      parameters: 
        - in: path
          name: officeId
          schema:
            type: string
          required: true
      responses:
        '200':  
          description: success
    
  /queue/{officeId}/{day}:
    post:
      tags: [queue]
      parameters:
        - in: path
          name: officeId
          schema:
            type: string
          required: true
        - in: path
          name: day
          schema:
            type: string
            format: date
          required: true
      requestBody:
        description: the new patient
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppointmentBase'
      responses:
        '200':
          description: success
    put:
      tags: [queue]
      description: replace the whole queue
      parameters: 
        - in: path
          name: officeId
          schema:
            type: string
          required: true
        - in: path
          name: day
          schema:
            type: string
            format: date
          required: true
      requestBody:
        description: the new patient
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/AppointmentBase'
      responses:
        '200':
          description: success
  /queue/{officeId}/{day}/{patientId}:
    get:
      tags: [queue]
      parameters: 
        - in: path
          name: officeId
          schema:
            type: string
          required: true
        - in: path
          name: patientId
          schema:
            type: integer
          required: true
        - in: path
          name: day
          schema:
            type: string
            format: date
          required: true
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
    put:
      tags: [queue]
      parameters: 
        - in: path
          name: officeId
          schema:
            type: string
          required: true
        - in: path
          name: patientId
          schema:
            type: integer
          required: true
        - in: path
          name: day
          schema:
            type: string
            format: date
          required: true
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AppointmentChange'
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
    delete:
      tags: [queue]
      parameters: 
        - in: path
          name: officeId
          schema:
            type: string
          required: true
        - in: path
          name: patientId
          schema:
            type: integer
          required: true
        - in: path
          name: day
          schema:
            type: string
            format: date
          required: true
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Appointment'
components:
  schemas:
    Office:
      description: medical office
      type: object
      properties:
        id:
          type: string
    Appointment:
      allOf:
        - $ref: '#/components/schemas/AppointmentBase'
        - type: object
          properties:
            place:
              type: integer
            estimateWaitingMinutes:
              type: integer
    AppointmentBase:
      description: an appointment
      type: object
      properties:
        time: 
          type: string
          format: datetime
        patientId:
          type: string
        notifications:
          type: array
          items:
            type: object
            properties:
              type: 
                type: string
                enum: [app, sms, beeper]
              identifier: 
                description: appId when app, telefonnumber when sms, beeperId when beeper
                type: string
        estimatedInMinutes:
          type: integer
          default: 15
    AppointmentChange:
      description: change an appointment
      type: object
      properties:
        notifications:
          type: array
          items:
            type: string